<a href="https://colab.research.google.com/github/iamkishan98/Deep-Learning-Coursera/blob/master/vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import time 

w = np.random.rand(1000)
x = np.random.rand(1000)
t1 = time.time()
z = np.dot(w,x)
t2 = time.time()
print(z)
print(str(1000*(t2-t1))+"ms")

z2 =0
t3 = time.time()
for i in range(0,1000):
  z2 = z2 + (w[i]*x[i])
t4 = time.time()
print(z2)
print(str(1000*(t4-t3))+"ms")

u = np.random.rand(5)
v = np.array([1,2,3,4])
z3 = np.exp(v)
print(z3)

244.45058226630584
0.09608268737792969ms
244.450582266306
1.6748905181884766ms
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [15]:
# Broadcasting In  python
import numpy as np

a =[1,2,3]
b=[5]
c = a+b
print(c)
# Broadcasting does not work for List in the python , it only works for Numpy array

d =np.array([[2,3,4,5],[10,45,7,8]])
e = [4,7,8,6]
f = d+e
print(f)

#x =np.array([[4,5,6,7],[10,11,12,13]])
#y = np.array([3,4])
#z = x+y
#print(z) 

print(f.shape)
assert(f.shape==(2,4))
f.reshape(4,2)
print(f)

[1, 2, 3, 5]
[[ 6 10 12 11]
 [14 52 15 14]]
(2, 4)
[[ 6 10 12 11]
 [14 52 15 14]]
